"""tmachine table

Revision ID: 8535f6174234
Revises: 
Create Date: 2018-05-04 09:20:37.504424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8535f6174234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmachine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definicia', sa.String(length=100), nullable=True),
    sa.Column('tm_d_n_x', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tmachine_definicia'), 'tmachine', ['definicia'], unique=True)
    op.create_index(op.f('ix_tmachine_tm_d_n_x'), 'tmachine', ['tm_d_n_x'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tmachine_tm_d_n_x'), table_name='tmachine')
    op.drop_index(op.f('ix_tmachine_definicia'), table_name='tmachine')
    op.drop_table('tmachine')
    # ### end Alembic commands ###
